// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJzD1q3pHDaDZ3ROxN2ai2OdOpUqivuYs',
    appId: '1:31120846839:web:1af678fe47bded868348f2',
    messagingSenderId: '31120846839',
    projectId: 'barodachestgroup-b6b77',
    authDomain: 'barodachestgroup-b6b77.firebaseapp.com',
    storageBucket: 'barodachestgroup-b6b77.appspot.com',
    measurementId: 'G-MT718NKCYT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaoqzTXZvF9uzSDBvvj_Y8efsrhCb2SG4',
    appId: '1:31120846839:ios:fe3a939c37ae4e7d8348f2',
    messagingSenderId: '31120846839',
    projectId: 'barodachestgroup-b6b77',
    storageBucket: 'barodachestgroup-b6b77.appspot.com',
    androidClientId: '31120846839-tj54bsstcsr4dn2s9o5ahjbs3d7s6u3d.apps.googleusercontent.com',
    iosClientId: '31120846839-po4jg2vmf4g8ssrk4ong3n72q9v9orgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.barodaChestGroupAdmin.RunnerTests',
  );
}
